### ISSUE TITLE
Add iframe titles to videos

### ISSUE THREAD

**Issue by katjam** [TheLabCollective/vector#234]

**Comment by Nikomus** [comment]
Advice from https://web.dev/frame-title/
> Additionally, best practice is to give the enclosed document a title element with content identical to the title attribute.

The videos are being reuploaded so, the title on the document will be `Video Title - YouTube` - we can make the iframe title match this.

**Comment by katjam** [comment]
@Nikomus I think we can close this. Unless you want to do a systematic check.
